HWRK_W5D1/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:new, :index]
end

HWRK_W5D1/MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string
#  live       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  band_id    :integer
#

class Album < ApplicationRecord
  validates :name, :live, :band_id, presence: true

  belongs_to :band
  has_many :tracks
end

HWRK_W5D1/MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

HWRK_W5D1/MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums
  
end

HWRK_W5D1/MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string
#  bonus      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  album_id   :integer
#

class Track < ApplicationRecord
  validates :name, :bonus, :album_id, presence: true

  belongs_to :album

end

HWRK_W5D1/MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  attr_reader :password
  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def reset_session_token
    session_token = self.class.generate_session_token
    self.save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end



end

HWRK_W5D1/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  before_action :check_login

  def check_login
    redirect_to(new_session_url, status: 303) unless logged_in?
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in_user!(user)
    user.reset_session_token
    session[:session_token] = user.session_token
  end
end

HWRK_W5D1/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController


  def index
    @bands = Band.all
  end

  def show
    @band = Band.find_by(id: params[:id])
  end

  def new
    @band = Band.new
    render :band_form
  end


  def create
    new_band = Band.new(bands_params)
    if new_band.save
      redirect_to band_url(new_band)
    else
      flash[:errors] = new_band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :band_form
  end

  def update
    band =  Band.find_by(id: params[:id])
    if band.save
      redirect_to band_url(new_band)
    else
      flash[:errors] = band.errors.full_messages
      redirect_to edit_band_url
    end
  end

  def destroy
    Band.destroy(params[:id])
  end

  private
  def bands_params
    params.require(:band).permit(:name)
  end
end

HWRK_W5D1/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(user_params[:email], user_params[:password])
    if user
      log_in_user!(user)
      redirect_to bands_url
    else
      flash[:errors] = ['Incorrect credentials']
      redirect_to new_session_url
    end
  end

  def destroy
    current_user.reset_session_token
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def check_login
    redirect_to bands_url, status: 303 if logged_in?
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

HWRK_W5D1/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def show

  end

  def create
    user = User.new(user_params)
    puts user
    if user.save
      log_in_user!(user)
      redirect_to user_url(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def check_login
    redirect_to bands_url, status: 303 if logged_in?
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

HWRK_W5D1/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input
    type='hidden'
    name='authenticity_token'
    value= #{form_authenticity_token} >".html_safe
  end

  def change_method(method)
    "<input
    type='hidden'
    name=\"_method\"
    value= #{method} >".html_safe
  end
end

HWRK_W5D1/MusicApp/app/views/bands/_band.html.erb
<li> <%= link_to "#{band.name}", band_url(band), controller: 'bands' %>  </li>

HWRK_W5D1/MusicApp/app/views/bands/band_form.html.erb
<%=  flash[:errors]%>
<form action="<%= @band.persisted? ? album_url : new_band_url %>" method="post">
  <%= auth_token %>
  <%= change_method('update') if @band.persisted? %>
  <label for="name">Band Name:</label>
  <input id = 'name' type="text" name="band[name]" value="<%= @band.name %>">
  <input type="submit" name="" value="submit">
</form>

HWRK_W5D1/MusicApp/app/views/bands/index.html.erb
<h1>BANDS</h1>
<ul>
  <%= render @bands%>

</ul>
<%= link_to "Make New Band", new_band_url%>

HWRK_W5D1/MusicApp/app/views/bands/show.html.erb
<p>
  <%= @band.name %>
  <%= link_to 'Edit', edit_band_url(@band) %>
</p>

HWRK_W5D1/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if logged_in? %>
        Logged in as: <%= current_user.email %>
        <form action=" <%= session_url %>" method="post">
          <%= auth_token %>
          <input type="hidden" name="_method" value="delete">
          <button type="submit" name="">Log Out</button>
      </form>
    <% else %>
    <% end %>

    <%= link_to "All Bands", bands_url, controller: 'bands' if logged_in? %>
    <%= yield %>
  </body>
</html>